[package]
name = "verinfo"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
# Compiler version
rustc_version_runtime = "0.3.0"

[build-dependencies]
anyhow.workspace = true
